version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      -postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/.env
    restart: always
  
  backend:
    image: artemhub/foodgram:latest
    restart: always

    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
    - ../backend/foodgram/.env

  frontend:
    image: artemhub/foodgram:latest

    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - static_value:/static/
      - media_value:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
