version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ..env
  
  backend:
    image: artemhub/foodgram:v2
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: artemhub/fronted:v1
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3
    ports:
      - '8080:80'
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
