# Generated by Django 2.2.16 on 2022-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221018_2017'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='list_item_unique',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='item',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='list_item_unique'),
        ),
    ]
